### ISSUE TITLE
Custom cell rendered are broken on restoring layout with a summary column

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1369]
**Steps to reproduce:**
1. Open a table/apply layout so that there are some custom cell renderers
2. Add a summary column
3. Save layout
4. Re-apply layout

**Expected results:** layout is applied, both custom cell renderers and summary columns are applied.

**Actual results:** custom cell renderers are not applied.
Error that could be related:
`rxjs.umd.min.js?56610:24 Uncaught TypeError: Cannot read properties of null (reading 'isVirtual')
    at listeners.js:234:17
    at C7 (listeners.js:257:5)
    at listeners.js:309:9
    at Array.forEach (<anonymous>)
    at a._next (listeners.js:308:15)
    at a.__tryOrUnsub (rxjs.umd.min.js?56610:62:91)
    at a.next (rxjs.umd.min.js?56610:60:384)
    at a._next (rxjs.umd.min.js?56610:58:497)
    at a.next (rxjs.umd.min.js?56610:58:168)
    at d (rxjs.umd.min.js?56610:39:23)
    at events.ts:22:11
    at Function.$1 (login.dart.js?56610:278:69)
    at dart.aXE (zone.dart:1132:12)
    at d6p.zZ (zone.dart:1012:12)
    at d6p.H4 (zone.dart:909:14)
    at d5Q.ay (stream_impl.dart:330:5)
    at dart.o5.kT (stream_impl.dart:257:7)
    at dff.$1 (broadcast_stream_controller.dart:387:7)
    at x.a5U (broadcast_stream_controller.dart:328:9)
    at x.ay (broadcast_stream_controller.dart:386:5)
    at dart.xH.t (broadcast_stream_controller.dart:254:5)
    at J.ad (login.dart.js?56610:18204:35)
    at C.a8 (event_bus.dart:69:7)
    at Object.b7 (events.dart:126:18)
    at bu.yF (table_view.dart:925:5)
    at bu.LG (view.dart:254:7)
    at dart.dx6.$2 (grok_api.dart:274:53)
    at Object.fS (js_helper.dart:1521:16)
    at dart.dhd (js_helper.dart:1489:11)
    at js_dart2js.dart:667:13
    at TableView.loadLayout (view.ts:294:16)
    at c.<anonymous> (index.js:166:20)
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at o (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at c.<anonymous> (asyncToGenerator.js:19:12)
    at c.<anonymous> (package.js:471:400054)
    at index.js:142:44
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at o (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at index.js:141:7
    at Array.map (<anonymous>)
    at o.<anonymous> (index.js:142:10)
    at f (regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (regeneratorRuntime.js:125:22)
    at Generator.next (regeneratorRuntime.js:69:21)
    at o (asyncToGenerator.js:3:20)
    at a (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at o.<anonymous> (asyncToGenerator.js:19:12)
    at o.<anonymous> (package.js:471:411446)
    at o.<anonymous> (index.js:159:18)
    at f (regeneratorRuntime.js:44:17)`

**Comment by skalkin** [comment]
Hi @katerina-stepanova , sorry I can't reproduce it; custom sparklines work just fine with molecule renderers. If you mean dynamic code-based rendering like in [this example](https://public.datagrok.ai/js/samples/grid/custom-cell-rendering-indexes),  then this is the expected behavior.

Please feel free to reopen!

**Comment by gasserandreas** [comment]
We double checked this on our end and the issue seems to be on our end. Sorry for any inconvenience!!
