### ISSUE TITLE
Chem | R-group analysis:  layout applying issue

### ISSUE THREAD

**Issue by ahadzhanian** [datagrok-ai/public#1385]
Platform: Public Version: 1.10.2 Chem 1.4.6

Data: any data with molecular column, [smiles](https://public.datagrok.ai/f/Demo.TestJobs.Files.DemoFiles/chem/smiles.csv)
To reproduce:

1. Go to **Chem** > **R-Group Analysis**
2. Click **MCS** and OK
3. Go to **Tables** > **Layouts** and click **SAVE**
4. Open another dataset, for example [smiles_only](https://public.datagrok.ai/f/Demo.TestJobs.Files.DemoFiles/chem/smiles_only.csv)
5. Go to **Tables** > **Layouts**
6. Locate the saved layout with R-Groups Analysis and click it

**Expected result**: layout applied to the datat 
**Actual result**:  Error loading Trellis plot

![Image](https://user-images.githubusercontent.com/111368431/209107368-abfc26aa-3323-4992-9ea4-cf0c8f1a71b0.gif)

NullError: method not found: 'gb5' on null
        TypeError: Cannot read properties of null (reading 'gb5')
            at dart.cSY.$2 (/login.dart.js_1.part.js?46459:38811:38)
            at au.iQ (login.dart.js:696:26)
            at J.rn (login.dart.js:18002:37)
            at MI.gabG (/login.dart.js_1.part.js?46459:38134:26)
            at MI.Jq (/login.dart.js_1.part.js?46459:38221:22)
            at MI.c5 (/login.dart.js_1.part.js?46459:38225:27)
            at MI.dI (/login.dart.js_1.part.js?46459:38155:6)
            at dart.d_O.$1 (/login.dart.js_1.part.js?46459:41586:3)
            at dart.aWs (login.dart.js:3914:35)
            at d4l.zT (login.dart.js:5668:12)
            at d4l.GV (login.dart.js:5623:12)
            at d3M.ax (login.dart.js:5134:8)
            at dart.nZ.kS (login.dart.js:5109:14)
            at ddc.$1 (login.dart.js:4158:18)
            at x.a5Q (login.dart.js:4131:3)
            at x.ax (login.dart.js:4151:13)
            at MJ.a_M (login.dart.js:15658:3)
            at MJ.dU (login.dart.js:15660:27)
            at MJ.Kv (/login.dart.js_1.part.js?46459:41361:6)
            at MJ.ha (/login.dart.js_1.part.js?46459:41362:28)
            at MI.xW (/login.dart.js_1.part.js?46459:41457:27)
            at cT_.an9 (/login.dart.js_1.part.js?46459:16686:9)
            at cT_.zd (/login.dart.js_1.part.js?46459:16690:32)
            at J.Tk (login.dart.js:18270:36)
            at cNE.$2 (/login.dart.js_1.part.js?46459:161744:5)
            at ji.aA_ (/login.dart.js_1.part.js?46459:75338:43)
            at Object.Yj (/login.dart.js_1.part.js?46459:75344:3)
            at bzN.aD0 (/login.dart.js_1.part.js?46459:76239:45)
            at bzN.afi (/login.dart.js_1.part.js?46459:76223:17)
            at dart.bzO.$1 (/login.dart.js_1.part.js?46459:76263:36)
            at au.aq (login.dart.js:677:20)
            at J.cl (login.dart.js:18003:35)
            at bzN.afi (/login.dart.js_1.part.js?46459:76222:3)
            at bzN.tx (/login.dart.js_1.part.js?46459:76212:8)
            at nB.tT (/login.dart.js_1.part.js?46459:75988:19)
            at bs.ZB (/login.dart.js_1.part.js?46459:161092:9)
            at bs.yB (/login.dart.js_1.part.js?46459:161081:19)
            at c4w.$1 (/login.dart.js_1.part.js?46459:132481:3)
            at dart.d6C.$1 (login.dart.js:12956:31)
            at dart.aWs (login.dart.js:3917:9)
            at d4l.zT (login.dart.js:5668:12)
            at d4l.GV (login.dart.js:5623:12)
            at dart.d4o.$1 (login.dart.js:5720:31)
            at fxZ.$0 (login.dart.js:3094:29)
            at Nx.L2 (login.dart.js:1848:9)
            at Object.FH (login.dart.js:1611:26)
            at dart.fxX (login.dart.js:2445:17)
            at HTMLDivElement.<anonymous> (login.dart.js:2453:53)

**Comment by MariaDolotova** [comment]
@ahadzhanian , I assume the error occurs because trellis plot has been constructed on exact columns (R1, R2, R3 and so on. The columns are the result of RGroup analysis script). And when you try to apply layout on a table which doesn't contain those columns, you get this error. Btw, if you try to apply layout on table containing required columns it will work correctly.


![Image](https://user-images.githubusercontent.com/44060410/214298599-1e46e553-2541-43ed-b7ce-ba0764705778.gif)

@dionissqq , @alex-aprm , please correct me if I'm mistaken.

**Comment by ahadzhanian** [comment]
Rechecked, the layout is applicable when there are columns (R1, R2, R3 and so on)
