### ISSUE TITLE
Snowflake Driver ClassNotFoundException

### ISSUE THREAD

**Issue by PavloPolovyi** [datagrok-ai/public#1579]
The “Snowflake” database connection is using an old driver class, FQDN com.snowflake.client.jdbc.SnowflakeDriver, and should be updated to use the newer net.snowflake.client.jdbc.SnowflakeDriver.

Please see documentation here: https://docs.snowflake.com/en/user-guide/jdbc-configure.html#jdbc-driver-class

There is an ClassNotFoundException when configuring the connection, stack trace below:

“Snowflake”: failed to connect:
ERROR:
`java.lang.ClassNotFoundException: com.snowflake.client.jdbc.SnowflakeDriver`

STACK TRACE:
```
java.lang.ClassNotFoundException: com.snowflake.client.jdbc.SnowflakeDriver
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at grok_connect.providers.JdbcDataProvider.prepareProvider(JdbcDataProvider.java:30)
at grok_connect.providers.JdbcDataProvider.getConnection(JdbcDataProvider.java:35)
at grok_connect.providers.JdbcDataProvider.testConnection(JdbcDataProvider.java:66)
at grok_connect.GrokConnect.lambda$connectorsModule$1(GrokConnect.java:132)
at spark.RouteImpl$1.handle(RouteImpl.java:72)
at spark.http.matching.Routes.execute(Routes.java:61)
at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1598)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
at org.eclipse.jetty.server.Server.handle(Server.java:516)
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by tcarolan** [comment]
Fixed for my version 1.14.1.  Thank you.
