### ISSUE TITLE
NoSuchMethodError when using Chemprop ML library

### ISSUE THREAD

**Issue by tcarolan** [datagrok-ai/public#1755]
When training a ML Model using the Chemprop library I receive a strange error message somehow related to AWS. Looks like a 'null' handling problem. 

URL from Chrome Developer Tools: https://datagrok-cvm.neomorph.com/grok_compute/modeling/train?id=7e8ac050-c640-11ed-85e2-41ae5d68c83a&type=Chemprop&table_server_url=http%3A%2F%2Finternal-ds-datagrok-prod-int-1387272864.us-west-2.elb.amazonaws.com%2Fapi&table_token=7e48fc60-c640-11ed-bd0f-1bfbb9df05dd&predict=molregno

This URL receives a 400 response.

I'm happy to do a screenshare to show you the issue or provide more details.

Server Error below:
2023-03-30T18:11:44 [error] (636100929) NoSuchMethodError: The getter 'statusCode' was called on null.
2023-03-30T18:11:44 Receiver: null
2023-03-30T18:11:44 Tried calling: statusCode
2023-03-30T18:11:44     #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
2023-03-30T18:11:44     #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
2023-03-30T18:11:44     #2      Storage&AmazonApi.handleErrors (package:datlas/src/aws/amazon_credentials_provider.dart:163)
2023-03-30T18:11:44     <asynchronous suspension>
2023-03-30T18:11:44     #3      AmazonCloudStorage.writeFileStream.<anonymous closure> (package:datlas/src/services/storage.dart:604)
2023-03-30T18:11:44     <asynchronous suspension>
2023-03-30T18:11:44     #4      _rootRunUnary (dart:async/zone.dart:1128)
2023-03-30T18:11:44     #5      _CustomZone.runUnary (dart:async/zone.dart:1012)
2023-03-30T18:11:44     #6      _FutureListener.handleValue (dart:async/future_impl.dart:129)
2023-03-30T18:11:44     #7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
2023-03-30T18:11:44     #8      _Future._propagateToListeners (dart:async/future_impl.dart:665)
2023-03-30T18:11:44     #9      _Future._completeWithValue (dart:async/future_impl.dart:478)
2023-03-30T18:11:44     #10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:510)
2023-03-30T18:11:44     #11     _rootRun (dart:async/zone.dart:1120)
2023-03-30T18:11:44     #12     _CustomZone.run (dart:async/zone.dart:1001)
2023-03-30T18:11:44     #13     _CustomZone.runGuarded (dart:async/zone.dart:901)
2023-03-30T18:11:44     #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
2023-03-30T18:11:44     #15     _microtaskLoop (dart:async/schedule_microtask.dart:41)
2023-03-30T18:11:44     #16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
2023-03-30T18:11:44     #17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
2023-03-30T18:11:44     #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

**Comment by LaykDimon** [comment]
We couldn't reproduce the problem on the client side, so I guess the problem is now closed.

**Comment by ahadzhanian** [comment]
Can't reproduce the issue on public 1.16.7
