### ISSUE TITLE
Error on adding a custom viewer

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#1838]
Following error occurs when a custom viewer is added:
`shell.ts:249 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at get tableNames [as tableNames] (shell.ts:249:5)
    at get tables [as tables] (shell.ts:255:17)
    at ny (dataframe.js:16:21)
    at n.value (index.jsx:54:20)
    at n.value (index.js:393:10)
    at n.value (index.jsx:24:5)
    at n.onFrameAttached (viewer.ts:354:10)
    at c8.fQ (login.dart.js?270:460:27)
    at J.Un (login.dart.js?270:18610:34)
    at kj.sO (js_viewer_host_core.dart:43:25)
    at dart.dFU.$2 (grok_api.dart:541:68)
    at Object.fX (js_helper.dart:1521:16)
    at dart.dlq (js_helper.dart:1489:11)
    at js_dart2js.dart:667:13
    at set dataFrame [as dataFrame] (viewer.ts:172:9)
    at n.value (index.jsx:55:10)
    at n.value (index.js:393:10)
    at n.value (index.jsx:24:5)
    at n.onFrameAttached (viewer.ts:354:10)
    at c8.fQ (login.dart.js?270:460:27)
    at J.Un (login.dart.js?270:18610:34)
    at kj.sO (js_viewer_host_core.dart:43:25)
    at dart.dFU.$2 (grok_api.dart:541:68)
    at Object.fX (js_helper.dart:1521:16)
    at dart.dlq (js_helper.dart:1489:11)
    at js_dart2js.dart:667:13
    at set dataFrame [as dataFrame] (viewer.ts:172:9)
    at n.value (index.jsx:55:10)
    at n.value (index.js:393:10)
    at n.value (index.jsx:24:5)
    at n.onFrameAttached (viewer.ts:354:10)
    at c8.fQ (login.dart.js?270:460:27)
    at J.Un (login.dart.js?270:18610:34)
    at kj.sO (js_viewer_host_core.dart:43:25)
    at dart.dFU.$2 (grok_api.dart:541:68)
    at Object.fX (js_helper.dart:1521:16)
    at dart.dlq (js_helper.dart:1489:11)
    at js_dart2js.dart:667:13
    at set dataFrame [as dataFrame] (viewer.ts:172:9)
    at n.value (index.jsx:55:10)
    at n.value (index.js:393:10)
    at n.value (index.jsx:24:5)
    at n.onFrameAttached (viewer.ts:354:10)
    at c8.fQ (login.dart.js?270:460:27)
    at J.Un (login.dart.js?270:18610:34)
    at kj.sO (js_viewer_host_core.dart:43:25)
    at dart.dFU.$2 (grok_api.dart:541:68)
    at Object.fX (js_helper.dart:1521:16)
    at dart.dlq (js_helper.dart:1489:11)
    at js_dart2js.dart:667:13
    at set dataFrame [as dataFrame] (viewer.ts:172:9)
    at n.value (index.jsx:55:10)
    at n.value (index.js:393:10)
    at n.value (index.jsx:24:5)
    at n.onFrameAttached (viewer.ts:354:10)
    at c8.fQ (login.dart.js?270:460:27)
    at J.Un (login.dart.js?270:18610:34)
    at kj.sO (js_viewer_host_core.dart:43:25)
    at dart.dFU.$2 (grok_api.dart:541:68)
    at Object.fX (js_helper.dart:1521:16)
    at dart.dlq (js_helper.dart:1489:11)
    at js_dart2js.dart:667:13
    at set dataFrame [as dataFrame] (viewer.ts:172:9)
    at n.value (index.jsx:55:10)`

**Comment by ahadzhanian** [comment]
let table = grok.data.testData('random walk', 1000, 2);
let view = grok.shell.addTableView(table);
and then:
let fc = Array.from(view.viewers)[1]
fc.add({type: "1"})

expected: no errors, just balloon
