### ISSUE TITLE
#3084: Packages: A package fails to handle credentials, app loading fails

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#3084]
v1.21.1

Following error is thrown:
```
#0      GrokServer.getCredentialsForEntity (package:datlas/src/grok_server.dart:376)
<asynchronous suspension>
#1      ConnectorsPlugin.getConnectionFilesImpl.<anonymous closure> (package:datlas/src/plugins/connectors/connectors.dart:356)
<asynchronous suspension>
#2      DbContext.run.<anonymous closure> (package:datlas/src/db_context.dart:401)
<asynchronous suspension>
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1001)
#5      runZoned (dart:async/zone.dart:1467)
#6      DbContext.run (package:datlas/src/db_context.dart:400)
<asynchronous suspension>
#7      GrokServerDbPlugin.dbRun (package:datlas/src/grok_server_plugin.dart:88)
<asynchronous suspension>
#8      ConnectorsPlugin.getConnectionFilesImpl (package:datlas/src/plugins/connectors/connectors.dart:336)
<asynchronous suspension>
#9      ConnectorsPlugin.getConnectionFiles.<anonymous closure> (package:datlas/src/plugins/connectors/connectors.dart:331)
<asynchronous suspension>
#10     ConnectorsPlugin.wrapCached (package:datlas/src/plugins/connectors/connectors.dart:319)
<asynchronous suspension>
#11     ConnectorsPlugin.getConnectionFiles (package:datlas/src/plugins/connectors/connectors.dart:327)
<asynchronous suspension>
#12     _LocalInstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:526)
#13     _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:522)
#14     _LocalClosureMirror.apply (dart:mirrors-patch/mirrors_impl.dart:550)
#15     ConstrainedFunctionProxy.invoke (package:constrain/constrained_function_proxy.dart:41)
#16     _wrapHandler.<anonymous closure> (package:shelf_bind/src/model/handler_bindings.dart:119)
<asynchronous suspension>
#17     HandlerBinding._handleRequest (package:shelf_bind/src/model/handler_bindings.dart:78)
#18     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31)
<asynchronous suspension>
#19     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27)
#20     RequestRouterImpl._createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:112)
#21     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31)
<asynchronous suspension>
#22     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27)
#23     _BaseRoute.createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:32)
<asynchronous suspension>
#24     GrokServer.authorize.<anonymous closure>.inner.<anonymous closure> (package:datlas/src/grok_server.dart:740)
#25     _rootRun (dart:async/zone.dart:1120)
#26     _CustomZone.run (dart:async/zone.dart:1001)
#27     runZoned (dart:async/zone.dart:1467)
#28     GrokServer.authorize.<anonymous closure>.inner (package:datlas/src/grok_server.dart:738)
#29     GrokServer.authorize.<anonymous closure> (package:datlas/src/grok_server.dart:768)
<asynchronous suspension>
#30     GrokServer.statistics.<anonymous closure> (package:datlas/src/grok_server.dart:670)
<asynchronous suspension>
#31     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70)
#32     new Future.sync (dart:async/future.dart:206)
#33     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70)
#34     _rootRunUnary (dart:async/zone.dart:1128)
#35     _CustomZone.runUnary (dart:async/zone.dart:1012)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:129)
#37     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
#38     _Future._propagateToListeners (dart:async/future_impl.dart:665)
#39     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:343)
#40     _rootRun (dart:async/zone.dart:1120)
#41     _CustomZone.run (dart:async/zone.dart:1001)
#42     _CustomZone.runGuarded (dart:async/zone.dart:901)
#43     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

Piece of code that is failaing:
```
  const packageCreds = await _package.getCredentials();
  const appConfig = {
    ...handleCredentials(packageCreds),
    urlParams,
  } as AppConfig;
```

**Comment by dnillovna** [comment]
This issue has been mirrored in Jira: https://reddata.atlassian.net/browse/GROK-16744
