### ISSUE TITLE
Filters saved on older DG versions are not restored

### ISSUE THREAD

**Issue by skalkin** [datagrok-ai/public#385]
Reported by a client

---------------

This morning we started our thorough testing of 0.139.0 on our DEV environment where we have lots of saved assays.

We immediately found a fairly major issue:

There seems to be an incompatibility (our assumption) between the filters saved by DG 0.112.8 and DG 0.139.0 which caused them to fail to restore.

Here’s the stack trace:

#1 (once in console)
Uncaught TypeError: Cannot read properties of undefined (reading 'G')

    at [Object.J.aW](http://object.j.aw/) (login.dart.js?92487:18110:33)

    at bEq.dart.bEq.$1 (filters_core.dart:206:28)

    at cR.j (iterable.dart:438:11)

    at rD.j (iterable.dart:390:9)

    at cR.j (iterable.dart:437:12)

    at at.ga4 (iterable.dart:383:24)

    at at.gbV (iterable.dart:390:27)

    at Object.J.bX (login.dart.js?92487:18231:32)

    at p2.dart.p2.aH (filters_core.dart:269:9)

    at p2.dart.p2.aH [as bp] (login.dart.js_1.part.js?92487:17649:44)

    at p2.dg (filters_core.dart:287:7)

    at cV7.dart.cV7.$1 (viewer_base.dart:104:9)

    at d5t.G0 (zone.dart:1307:16)

    at cYY.at (stream_impl.dart:330:5)

    at [cYY.dart.nT.kw](http://cyy.dart.nt.kw/) (stream_impl.dart:257:7)

    at [u.at](http://u.at/) (broadcast_stream_controller.dart:379:7)

    at q1.YS (broadcast_stream_controller.dart:254:5)

    at q1.e1 (login.dart.js?92487:15818:27)

    at q1.Ji (look_and_feel.dart:93:5)

    at [q1.hk](http://q1.hk/) (login.dart.js_1.part.js?92487:37969:28)

    at p2.H7 (viewer_base.dart:42:5)

    at bEL.a7v (viewer_descriptor.dart:84:7)

    at bEL.ym (login.dart.js_1.part.js?92487:16092:32)

    at [Object.J.SU](http://object.j.su/) (login.dart.js?92487:18402:36)

    at cHP.$2 (table_view.dart:792:29)

    at iU.axx (panel_dock_container.dart:74:29)

    at Object.XK (panel_dock_container.dart:63:3)

    at bwW.aAx (dock_graph_deserializer.dart:62:19)

    at bwW.adA (dock_graph_deserializer.dart:38:32)

    at bwX.dart.bwX.$1 (dock_graph_deserializer.dart:33:28)

    at ao.an (js_array.dart:252:7)

    at Object.J.cp (login.dart.js?92487:18135:35)

    at bwW.adA (dock_graph_deserializer.dart:32:5)

    at bwW.rR (dock_graph_deserializer.dart:13:22)

    at ns.t9 (dock_manager.dart:388:17)

    at bt.XH (table_view.dart:811:5)

    at bt.DX (table_view.dart:770:86)

    at bt.Km (view.dart:230:7)

    at dmA.dart.dmA.$2 (grok_api.dart:308:53)

    at Object.fj (js_helper.dart:1521:16)

    at dart.d99 (js_helper.dart:1489:11)

    at js_dart2js.dart:667:13

    at p.loadLayout (view.ts:302:16)

    at a.<anonymous> (index.js:239:20)

    at s (runtime.js:63:40)

    at Generator._invoke (runtime.js:294:22)

    at Generator.next (runtime.js:119:21)

    at m (asyncToGenerator.js:3:20)

    at i (asyncToGenerator.js:25:9)

    at asyncToGenerator.js:32:7

    at new Promise (<anonymous>)

    at a.<anonymous> (asyncToGenerator.js:21:12)

    at a.<anonymous> (package.js:335:1287669)

    at n.value (index.js:193:25)

    at Portal.jsx:61:29

    at onSelect (index.jsx:97:31)

    at Object.o (react-dom.production.min.js:14:84)

    at p (react-dom.production.min.js:14:238)

    at react-dom.production.min.js:14:292

    at m (react-dom.production.min.js:15:72)

    at it (react-dom.production.min.js:52:170)

    at rt (react-dom.production.min.js:51:255)

    at ot (react-dom.production.min.js:52:334)

    at pt (react-dom.production.min.js:56:10)

    at R (react-dom.production.min.js:287:189)

    at Z (react-dom.production.min.js:19:57)

    at qt (react-dom.production.min.js:70:279)

    at Jt (react-dom.production.min.js:69:102)

    at t.unstable_runWithPriority (scheduler.production.min.js:19:467)

    at Ur (react-dom.production.min.js:122:325)

    at T (react-dom.production.min.js:287:48)

    at Xt (react-dom.production.min.js:68:371)

#2 (repeated in console, perhaps once for each filter column in the viewer?)
Uncaught TypeError: Cannot read properties of null (reading 'jL')

    at ctv.$0 (scatterplot_core.dart:219:21)

    at fgS.dart.fgS.$1 (html_utils.dart:738:28)

    at d5t.G0 (zone.dart:1307:16)

    at Nj.at (stream_impl.dart:330:5)

    at [Nj.dart.nT.kw](http://nj.dart.nt.kw/) (stream_impl.dart:257:7)

    at Nj.kw (stream_pipe.dart:132:5)

    at az.zX (stream_pipe.dart:207:7)

    at Nj.dart.Nj.aC4 (stream_pipe.dart:164:5)

    at TO.eval (eval at aGv (js_helper.dart:2811:12), <anonymous>:3:36)

    at d0M.dart.d0M.$1 (html_dart2js.dart:42920:48)

    at fji.$0 (js_helper.dart:2456:48)

    at No.JN (isolate_helper.dart:474:16)

    at Object.FD (isolate_helper.dart:59:16)

   at dart.fjg (js_helper.dart:2456:14)

    at HTMLDivElement.<anonymous> (js_helper.dart:2476:14)

**Comment by skalkin** [comment]
Fixed in v0.140. There was a bug with the backwards compatibility for categorical columns.
