### ISSUE TITLE
Row number is not clickable after applying saved layout

### ISSUE THREAD

**Issue by katerina-stepanova** [datagrok-ai/public#679]
**Steps to reproduce:**
1. Open a table (any)
*Notice that row is selected on clicking row number at the left.*
3. Save layout
4. Apply saved layout
5. Click some row number

**Expected results:** row selection by clicking row number should be working if saved layout is applied.
**Actual results:** nothing happens on clicking row number after applying saved layout.

**Comment by dgosi** [comment]
This problem is most likely related to the reported issues here https://github.com/datagrok-ai/public/issues/674

**Comment by alex-aprm** [comment]
Fixed, available in 1.1.10 or higher

**Comment by katerina-stepanova** [comment]
Incompatibility with layouts saved in earlier version (happens when old layout is applied and saved):
    
    Operation caused an exception
    js_primitives.dart:30 pgpool1:24975:6815 ERROR 23503 insert or update on table "view_layouts" violates foreign key constraint "view_layouts_author_id_fkey"
    js_primitives.dart:30 #0      RepoQuery.save (package:dinq/src/repository_query.dart:768)
    <asynchronous suspension>
    #1      ViewLayoutsRepository.save (package:datlas/src/repositories/layouts_repositories.dart:23)
    <asynchronous suspension>
    #2      LayoutService.postLayout.<anonymous closure> (package:datlas/src/plugins/layout.dart:130)
    <asynchronous suspension>
    #3      DbContext.run.<anonymous closure> (package:datlas/src/db_context.dart:376)
    <asynchronous suspension>
    #4      _rootRun (dart:async/zone.dart:1120)
    #5      _CustomZone.run (dart:async/zone.dart:1001)
    #6      runZoned (dart:async/zone.dart:1467)
    #7      DbContext.run (package:datlas/src/db_context.dart:375)
    <asynchronous suspension>
    #8      GrokServerDbPlugin.dbRun (package:datlas/src/grok_server_plugin.dart:88)
    <asynchronous suspension>
    #9      LayoutService.postLayout (package:datlas/src/plugins/layout.dart:128)
    #10     _LocalInstanceMirror._invoke (dart:mirrors-patch/mirrors_impl.dart:526)
    #11     _LocalInstanceMirror.invoke (dart:mirrors-patch/mirrors_impl.dart:522)
    #12     _LocalClosureMirror.apply (dart:mirrors-patch/mirrors_impl.dart:550)
    #13     ConstrainedFunctionProxy.invoke (package:constrain/constrained_function_proxy.dart:41)
    #14     _wrapHandler.<anonymous closure> (package:shelf_bind/src/model/handler_bindings.dart:119)
    <asynchronous suspension>
    #15     HandlerBinding._handleRequest (package:shelf_bind/src/model/handler_bindings.dart:78)
    #16     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31)
    <asynchronous suspension>
    #17     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27)
    #18     RequestRouterImpl._createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:112)
    #19     DefaultSegmentRouter.handle (package:shelf_route/src/default_segment_router.dart:31)
    <asynchronous suspension>
    #20     _BaseRoute.handle (package:shelf_route/src/route_impl.dart:27)
    #21     _BaseRoute.createHandler.<anonymous closure> (package:shelf_route/src/route_impl.dart:32)
    <asynchronous suspension>
    #22     GrokServer.authorize.<anonymous closure>.inner.<anonymous closure> (package:datlas/src/grok_server.dart:510)
    #23     _rootRun (dart:async/zone.dart:1120)
    #24     _CustomZone.run (dart:async/zone.dart:1001)
    #25     runZoned (dart:async/zone.dart:1467)
    #26     GrokServer.authorize.<anonymous closure>.inner (package:datlas/src/grok_server.dart:508)
    #27     GrokServer.authorize.<anonymous closure> (package:datlas/src/grok_server.dart:560)
    <asynchronous suspension>
    #28     logRequests.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:datlas/src/utils/errors.dart:130)
    #29     new Future.sync (dart:async/future.dart:206)
    #30     logRequests.<anonymous closure>.<anonymous closure> (package:datlas/src/utils/errors.dart:130)
    #31     GrokServer.statistics.<anonymous closure> (package:datlas/src/grok_server.dart:443)
    <asynchronous suspension>
    #32     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70)
    #33     new Future.sync (dart:async/future.dart:206)
    #34     createMiddleware.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:shelf/src/middleware.dart:70)
    #35     _rootRunUnary (dart:async/zone.dart:1128)
    #36     _CustomZone.runUnary (dart:async/zone.dart:1012)
    #37     _FutureListener.handleValue (dart:async/future_impl.dart:129)
    #38     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:636)
    #39     _Future._propagateToListeners (dart:async/future_impl.dart:665)
    #40     _Future._addListener.<anonymous closure> (dart:async/future_impl.dart:343)
    #41     _rootRun (dart:async/zone.dart:1120)
    #42     _CustomZone.run (dart:async/zone.dart:1001)
    #43     _CustomZone.runGuarded (dart:async/zone.dart:901)
    #44     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:926)
    #45     _microtaskLoop (dart:async/schedule_microtask.dart:41)
    #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
    #47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
    #48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)

**Comment by alex-aprm** [comment]
Fixed too. In 1.3.2
